name: Pull Request CI

on:
  pull_request:
    branches:
      - "main"

jobs:
  testing:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.11"]
        netbox-version: ["v4.0.3"]
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      postgres:
        image: postgres
        env:
          POSTGRES_USER: netbox
          POSTGRES_PASSWORD: netbox
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: netbox-cloudflare-plugin
      - name: Checkout netbox ${{ matrix.netbox-version }}
        uses: actions/checkout@v3
        with:
          repository: "netbox-community/netbox"
          ref: ${{ matrix.netbox-version }}
          path: netbox
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install netbox_cloudflare_plugin Dependencies
        working-directory: netbox-cloudflare-plugin
        run: |
          pip install .
          pip install requests_mock
      - name: Install netbox Dependencies
        working-directory: netbox
        run: |
          ln -s $(pwd)/../netbox-cloudflare-plugin/netbox_configuration/configuration_testing.py netbox/netbox/configuration.py
          python -m pip install --upgrade pip
          pip install -r requirements.txt -U
      - name: Run Pylint
        run: |
          pip install pylint
          pylint --rcfile $(pwd)/netbox-cloudflare-plugin/.pylintrc --init-hook 'import os; import sys; sys.path.append(os.getcwd() + "/netbox/netbox")' $(pwd)/netbox-cloudflare-plugin/netbox_cloudflare_plugin/
      - name: Start Mockserver
        working-directory: netbox-cloudflare-plugin
        run: docker run -v ./netbox_cloudflare_plugin/tests/mockserver/config:/config -e MOCKSERVER_INITIALIZATION_JSON_PATH=/config/initializerJson.json -p 1080:1080 -d mockserver/mockserver
      - name: Run tests with coverage and edit coverage report
        working-directory: netbox
        run: |
          python3 -m pip install coverage
          coverage run --include='*/netbox_cloudflare_plugin/*' netbox/manage.py test netbox_cloudflare_plugin.tests -v 2
          coverage report -m
          coverage xml -o coverage.xml
